/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Latihan10.minggu3.hari1;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
